### ISSUE TITLE
VectorLink load JSON error

### ISSUE THREAD

**Issue by timathom** [yale-datachemist/entity-resolution#41]
After installing VectorLink from the `generic_storage` branch, I ran the load command as follows:

```
vectorlink load -k $OPENAI_KEY -c fakecommit --domain loc -d /home/DataChemist/data/vector_storage -i authority_ops.json --size 8738134 --build-index true -m small3 -q > error.txt
```

On the first run, it halted with an error:

```
saved embeddings
indexed 1806900
start of loop
retrieved embeddings
saved embeddings
indexed 1807000
start of loop
thread 'main' panicked at vectorlink/src/main.rs:532:14:
called `Result::unwrap()` on an `Err` value: VectorizationError(EmbeddingError(BadJson(Error("expected `,` or `]`", line: 82906, column: 17))))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I set `RUST_BACKTRACE=1` and ran again:

```
saved embeddings
indexed 1041300
rate limit time!
start of loop
retrieved embeddings
saved embeddings
indexed 1041400
rate limit time!
start of loop
thread 'main' panicked at vectorlink/src/main.rs:532:14:
called `Result::unwrap()` on an `Err` value: VectorizationError(EmbeddingError(BadJson(Error("expected value", line: 123805, column: 1))))
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: vectorlink::main::{{closure}}
   4: tokio::runtime::park::CachedParkThread::block_on
   5: tokio::runtime::runtime::Runtime::block_on
   6: vectorlink::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I set `RUST_BACKTRACE=full` and tried again. This time, it _seemed_ to finish retrieving the embeddings. The size of the `vectors` file in `vector_storage/.staging/loc/` was 46G, which was about the same as the final size previously. However, the process seemed to hang without building the index:

```
minute passed. budget now 895000
minute passed. budget now 907253
minute passed. budget now 921139
minute passed. budget now 936464
minute passed. budget now 939808
minute passed. budget now 951596
minute passed. budget now 963148
minute passed. budget now 974496
minute passed. budget now 987415
minute passed. budget now 1000000
``` 

So, I stopped the process and manually copied the `vectors` file from `vector_storage/.staging/loc/vectors` to `vector_storage/loc.vecs`. Then I ran the `index` command:

```
vectorlink index --directory /home/DataChemist/data/vector_storage --domain loc --commit pq8-take-1 --key fake -q > error2.txt
```

The process seemed to complete successfully:

```
opened "/home/DataChemist/data/vector_storage/.staging/loc/pq8-take-1/index.hnsw/hnsw/layer.nodes.0" for layer 0
wrote nodes for layer 0
opened File { fd: 14, path: "/home/DataChemist/data/vector_storage/.staging/loc/pq8-take-1/index.hnsw/hnsw/layer.neighbors.0", read: false, write: true } for layer 0
wrote neighbors for layer 0
serializing comparator
opened comparator serialize file
serialized comparator
wrote comparator to file
done serializing hnsw
renaming "/home/DataChemist/data/vector_storage/.staging/loc/pq8-take-1/index.hnsw" to "/home/DataChemist/data/vector_storage/loc@pq8-take-1.hnsw"
```

But when I try to run a search using:

```
vectorlink search-server --key $OPENAI_KEY --size 4500000 --directory ~/data/vector_storage --domain 'loc' --commit pq8-take-1 -o ~/src/entity-resolution/authority_ops.json
```

Results are not relevant, and every distance is coming back around 0.45.

**Comment by matko** [comment]
Issue seems to be that openai is returning something that is not parsable as a json.
I modified this branch to include the entire document that fails to parse. Could you rerun (with `RUST_BACKTRACE=full`) and report what the error is?

**Comment by timathom** [comment]
@matko, I ran:
```
nix run github:terminusdb-hub/vectorlink/generic_storage#vectorlink --refresh --extra-experimental-features nix-command --extra-experimental-features flakes
```
Is that right? Will that get me the latest commit?

This was the output I got, and it doesn't include the document: 🤔
```
indexed 641400
start of loop
thread 'main' panicked at vectorlink/src/main.rs:532:14:
called `Result::unwrap()` on an `Err` value: VectorizationError(EmbeddingError(BadJson(Error("expected `,` or `]`", line: 97874, column: 12))))
stack backtrace:
   0:     0x55d87942dc65 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hbaf8fc189101dfe8
   1:     0x55d879456f8b - core::fmt::write::hf660ac4eb6f2add1
   2:     0x55d87942a60f - std::io::Write::write_fmt::h0aa23be0bd9cfa0c
   3:     0x55d87942ef61 - std::panicking::default_hook::{{closure}}::h9a3ea3db17847643
   4:     0x55d87942ec3c - std::panicking::default_hook::h78fb7d1fff374982
   5:     0x55d87942f631 - std::panicking::rust_panic_with_hook::h29b0bcc55ace85de
   6:     0x55d87942f497 - std::panicking::begin_panic_handler::{{closure}}::he940321d814d7e45
   7:     0x55d87942e129 - std::sys::backtrace::__rust_end_short_backtrace::h8333ddb76a6f1f6a
   8:     0x55d87942f124 - rust_begin_unwind
   9:     0x55d879454743 - core::panicking::panic_fmt::h3883036404a69a62
  10:     0x55d879454c16 - core::result::unwrap_failed::h6efaafb729d50e24
  11:     0x55d878fa7c04 - vectorlink::main::{{closure}}::hcfa3244472e89249
  12:     0x55d878f6e51d - tokio::runtime::park::CachedParkThread::block_on::h929c259ffe17ce3c
  13:     0x55d879043961 - tokio::runtime::runtime::Runtime::block_on::h1f7533ff01605ad2
  14:     0x55d878fa0ffa - vectorlink::main::h9fd813fc6b14d52e
  15:     0x55d878fedc13 - std::sys::backtrace::__rust_begin_short_backtrace::h19d276ed41c1e147
  16:     0x55d87908a1c9 - std::rt::lang_start::{{closure}}::hb169bdcba62fcf16
  17:     0x55d879421a40 - std::rt::lang_start_internal::h8a402ec7b92c5251
  18:     0x55d878fab0ac - main
  19:     0x7f4414e3d10e - __libc_start_call_main
  20:     0x7f4414e3d1c9 - __libc_start_main@GLIBC_2.2.5
  21:     0x55d878e485c5 - _start
  22:                0x0 - <unknown>
```

**Comment by timathom** [comment]
@matko Well, now I am struggling to reproduce the issue. I did reproduce it once, but then I realized that I hadn't correctly updated my VectorLink install to your latest commit, so the full output wasn't included in the backtrace. Now I'm just spending API credits trying to reproduce it 🤦🏻‍♂️
